theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true  
github:
  is_project_page: false

title: A Multi-Scale Time-Frequency Spectrogram Discriminator for GAN-based Non-Autoregressive TTS
description:
  Haohan Guo<sup>1</sup>, Hui Lu<sup>1</sup>,  Xixin Wu<sup>1</sup>, Helen Meng<sup>1</sup> <br>
  <br>
  <sup>1</sup> The Chinese University of Hong Kong, Hong Kong SAR, China <br>
