theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true  
github:
  is_project_page: false

title: Demo Page
description:
  A Multi-Scale Time-Frequency Spectrogram Discriminator for GAN-based Non-Autoregressive TTS <br>
  <br>
  Haohan Guo, Hui Lu,  Xixin Wu, Helen Meng <br>
  <br>
  The Chinese University of Hong Kong, Hong Kong SAR, China <br>
